=== ajaletto/CSE_598_A9_A10/Aletto_Doyal_A9_A10/App_Data/member.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- W3C Schema generated by XMLSpy v2019 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Members">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="member" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Name">
		
	</xs:element>
	<xs:element name="PwdHash">
		
	</xs:element>
	<xs:element name="member">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name"/>
				<xs:element ref="PwdHash"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ajaletto/CSE_598_A9_A10/Aletto_Doyal_A9_A10/Members.xml
<?xml version="1.0" encoding="utf-8"?>
<Members xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/CSE598/CSE_598_A9_A10/Aletto_Doyal_A9_A10/App_Data/member.xsd">
  <member>
    <Name>Roy</Name>
    <PwdHash>A665A45920422F9D417E4867EFDC4FB8A04A1F3FFF1FA07E998E86F7F7A27AE3</PwdHash>
  </member>
  <member>
    <Name>Jill</Name>
    <PwdHash>A665A45920422F9D417E4867EFDC4FB8A04A1F3FFF1FA07E998E86F7F7A27AE3</PwdHash>
  </member>
  <member>
    <Name>123</Name>
    <PwdHash>A665A45920422F9D417E4867EFDC4FB8A04A1F3FFF1FA07E998E86F7F7A27AE3</PwdHash>
  </member>
  <member>
    <Name>Tony</Name>
    <PwdHash>03AC674216F3E15C761EE1A5E255F067953623C8B388B4459E13F978D7C846F4</PwdHash>
  </member>
</Members>
